// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz5mutH6s30DfQW-eaqruQaXZ3By7qQVI',
    appId: '1:763267377619:web:61e3bf12fba7639f95a726',
    messagingSenderId: '763267377619',
    projectId: 'orion-ai-62710',
    authDomain: 'orion-ai-62710.firebaseapp.com',
    storageBucket: 'orion-ai-62710.firebasestorage.app',
    measurementId: 'G-C4M37NWL59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQJZP5M8BGazJfpeT1EQtAR4jXA4vNpw',
    appId: '1:763267377619:android:0ce424c83da0454995a726',
    messagingSenderId: '763267377619',
    projectId: 'orion-ai-62710',
    storageBucket: 'orion-ai-62710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQkfn4jkA0rU67GYsDA7vckwtsCNE3Y4',
    appId: '1:763267377619:ios:71f623f2d3c7632d95a726',
    messagingSenderId: '763267377619',
    projectId: 'orion-ai-62710',
    storageBucket: 'orion-ai-62710.firebasestorage.app',
    iosBundleId: 'com.example.orionAiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCQkfn4jkA0rU67GYsDA7vckwtsCNE3Y4',
    appId: '1:763267377619:ios:71f623f2d3c7632d95a726',
    messagingSenderId: '763267377619',
    projectId: 'orion-ai-62710',
    storageBucket: 'orion-ai-62710.firebasestorage.app',
    iosBundleId: 'com.example.orionAiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz5mutH6s30DfQW-eaqruQaXZ3By7qQVI',
    appId: '1:763267377619:web:fa18c039eeb5b5dc95a726',
    messagingSenderId: '763267377619',
    projectId: 'orion-ai-62710',
    authDomain: 'orion-ai-62710.firebaseapp.com',
    storageBucket: 'orion-ai-62710.firebasestorage.app',
    measurementId: 'G-YEY9L5PGE7',
  );
}
